### ISSUE TITLE
Deploy airflow on minikube

### ISSUE THREAD

**Issue by yuwtennis** [yuwtennis/workflow#1]
https://github.com/airflow-helm/charts/tree/main/charts/airflow

# Tasks

- [ ] Create charts
  - [ ] Deployment for PostgrSQL
  - [ ] Service for PostgreSQL
- [ ] Helm install Airflow]
