### ISSUE TITLE
Install local airflow on host os

### ISSUE THREAD

**Issue by yuwtennis** [yuwtennis/workflow#2]
# Task

- [x] Containerize _sheets-to-es_
- [x] Install airflow
- [ ] Install PostgreSQL in Docker
- [ ] Create DAG using [provider.docker_operator](https://github.com/apache/airflow/blob/master/airflow/providers/docker/example_dags/example_docker.py)
